cookie:
  expiry_days: 1
credentials:
  usernames:
    maha_seleem:
      failed_login_attempts: 0
      first_name: Maha
      last_name: Seleem
      logged_in: false
      password: '123456789'
      roles:
        - Reviewer
    test_user:
      failed_login_attempts: 0
      first_name: tester
      last_name: 
      logged_in: false
      password: '$2b$12$rjtNkE05v.Eq9mlUyiWdl.Ytptk/qZgg/FQlfSoRTXpnrtaF4qIzq'
      roles:
        - Reviewer
    Moo:
      failed_login_attempts: 0
      first_name: Alsaidy
      last_name: Mohamed
      logged_in: false
      password: Mohamed
      roles:
        - Reviewer
        - admin
    reda:
      failed_login_attempts: 0
      first_name: Mohamed
      last_name: Reda
      logged_in: false
      password: reda
      roles:
        - admin
    sss:
      failed_login_attempts: 0
      first_name: sss
      last_name: sss
      logged_in: false
      password: ssss
      roles:
        - user
        - admin
privileges:
  - view_data
  - export_reports
  - manage_users
  - configure_system
  - delete_data
roles:
  Reviewer:
    description: Regular user with basic accessss
    privileges:
      - view_data
      - export_reports
      - manage_users
  admin:
    description: "Full system administrator "
    privileges:
      - manage_users
      - delete_data
  gg:
    description: hh
    privileges:
      - view_data
      - export_reports
  user:
    description: Regular user with basic access
    privileges:
      - view_data
      - export_reports